main: "net.telentity.Telentity"
name: "Telentity"
version: ${project.version}
authors: [ TheMrJezza, WolfYangFan ]

# Telentity will function on all versions.
# Whether 3rd party 'Preventors' function relies on the
# individual Preventors themselves.
api-version: "1.13"